### ISSUE TITLE
Upgrade to 100.5.1?

### ISSUE THREAD

**Issue by MightyCreak** [LironEr/docker-mongodb-tools#1]
Hello!

I can see that there's the release 100.5.1 available on mongo website: https://www.mongodb.com/try/download/database-tools

Could it be possible to bump the release from 100.1.1 to this one?

Cheers!

**Comment by LironEr** [comment]
Just uploaded 100.5.1 to Docker Hub and GitHub container registry

**Comment by MightyCreak** [comment]
Hello!

Thanks for the update!

I was wondering, how come I don't see it here: https://github.com/LironEr/docker-mongodb-tools/blob/main/Dockerfile#L3 ?

**Comment by LironEr** [comment]
Good question (:
This is just the default value
When I create a new release the GitHub action takes the release name and set it as the `mongodb-tools` version
https://github.com/LironEr/docker-mongodb-tools/blob/main/.github/workflows/docker.yml#L79

With this action, I don't need to commit anything, just publish a new release when needed (:

**Comment by MightyCreak** [comment]
Ah! I understand! Thank you :wink:
